[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/details"
  to = "/pages/details.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/pages/index.html"
  status = 200
