[build]
  publish = "."
  command = "npm run build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/details"
  to = "/pages/details.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/pages/index.html"
  status = 200
